# Generated by Django 5.1.3 on 2024-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cajero',
            name='numero_caja',
            field=models.IntegerField(),
        ),
    ]
