# Generated by Django 5.1.3 on 2024-11-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='nombre',
            field=models.CharField(default='Activo', max_length=50, verbose_name='Estado de la agencia'),
        ),
    ]
