# Generated by Django 5.1.3 on 2024-12-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_local', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='updated',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Fecha de alta'),
        ),
    ]
