# Generated by Django 5.1.3 on 2024-12-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_local', '0002_alter_departamento_updated_alter_localidad_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='updated',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Fecha de modificacion'),
        ),
    ]
