# Generated by Django 5.1.3 on 2024-12-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_local', '0003_alter_provincia_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Creado'),
        ),
    ]
