# Generated by Django 5.1.3 on 2024-12-23 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_agenciero', '0002_remove_agenciero_created_remove_agenciero_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenciero',
            name='cbu',
            field=models.CharField(help_text='Introduzca el numero de CBU maximo 22 dijitos', max_length=22, unique=True, validators=[django.core.validators.RegexValidator('^\\d{22}$')], verbose_name='CBU'),
        ),
        migrations.AlterField(
            model_name='agenciero',
            name='foto',
            field=models.ImageField(default='imagenes/user/user.png', upload_to='agenciero'),
        ),
    ]
